services:
  - type: web
    name: backend
    env: python
    plan: starter
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://usuario:contraseña@host:puerto/subastas"
      - key: SECRET_KEY
        value: "tu_secret_jwt"
    autoDeploy: true

  - type: web
    name: frontend
    env: node
    plan: starter
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview -- --port $PORT"
    autoDeploy: true